export const memberKey = [
    "Member ID",
    "Name of Applicant",
    "Parent Name",
    "Phone Number",
    "WhatsApp Number",
    "Occupation",
    "Date Of Birth",
    "Gender",
    "Martial Status",
    "Pan Number",
    "Account Number",
    "IFSC Code",
    "Bank Name",
    "Branch Name",
    "Aadhar Number",
    "Address",
    "Name of the Nominee",
    "Relationship with Nominee",
  ];